# "How do i fail a task in Ansible if the variable contains a boolean value?
# I want to perform input validation for Ansible playbooks"
# https://stackoverflow.com/questions/46664127/how-do-i-fail-a-task-in-ansible-if-the-variable-contains-a-boolean-value-i-want/46667499#46667499

# We assume 0-init/tasks/validate_vars.yml has DEFINITELY been run, so no need
# to re-check whether vars are defined here.  As Ansible vars cannot be unset:
# https://serverfault.com/questions/856729/how-to-destroy-delete-unset-a-variable-value-in-ansible

- name: Assert that "vscode_server_install is sameas true" (boolean not string etc)
  assert:
    that: vscode_server_install is sameas true
    fail_msg: "PLEASE SET 'vscode_server_install: True' e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that "vscode_server_enabled | type_debug == 'bool'" (boolean not string etc)
  assert:
    that: vscode_server_enabled | type_debug == 'bool'
    fail_msg: "PLEASE GIVE VARIABLE 'vscode_server_enabled' A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes


- block:

    - name: Install VS Code Server if 'vscode_server_installed' not defined, e.g. in {{ iiab_state_file }}    # /etc/iiab/iiab_state.yml
      include_tasks: install.yml
      when: vscode_server_installed is undefined

    - include_tasks: enable-or-disable.yml

    - name: Add 'vscode-server' variable values to {{ iiab_ini_file }}
      ini_file:
        path: "{{ iiab_ini_file }}"    # /etc/iiab/iiab.ini
        section: vscode-server
        option: "{{ item.option }}"
        value: "{{ item.value | string }}"
      with_items:
        - option: name
          value: VS Code Server
        - option: description
          value: '"Browser-based Visual Studio Code IDE for learning programming and development."'
        - option: vscode_server_install
          value: "{{ vscode_server_install }}"
        - option: vscode_server_enabled
          value: "{{ vscode_server_enabled }}"
        - option: vscode_server_url
          value: "{{ vscode_server_url }}"
        - option: vscode_server_port
          value: "{{ vscode_server_port }}"
        - option: vscode_server_base
          value: "{{ vscode_server_base }}"

  rescue:

    - name: 'SEE ERROR ABOVE (skip_role_on_error: {{ skip_role_on_error }})'
      fail:
        msg: ""
      when: not skip_role_on_error
